; Wokwi: ESP32 + ILI9341 (simulacao)
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ILI9341
    bblanchon/ArduinoJson @ ^7.2.0
build_flags =
    -DCORE_DEBUG_LEVEL=0

; Hardware real: ESP32-S3 + JC4832W535 (480x320, AXS15231B)
[env:real]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    moononournation/GFX Library for Arduino @ ^1.4.9
    adafruit/Adafruit GFX Library
    bblanchon/ArduinoJson @ ^7.2.0
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DREAL_HARDWARE
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
